language: python

python:
    - "3.7"
    - "3.8"

install:
    - pip install tox-travis
    - pip install pytest tox

cache:
    directories:
        - $HOME/virtualenv

script:
    - tox

sudo: false
